### ISSUE TITLE
Add Support For Tooltips

### ISSUE THREAD

**Issue by ExiledLizard** [SyberiaK/colorful-hex#1]
I have an enhancement idea for your mod: "Colorful Hex", @SyberiaK  - tooltip support. So, if any item's tooltip has a hex color string (like: #3b7a57), it will become that color.

**Comment by SyberiaK** [comment]
Sounds good! I'll look into it once I got some spare time.

вт, 16 апр. 2024 г., 07:28 ExiledLizard ***@***.***>:

**Comment by ExiledLizard** [comment]
Alright, cool!

**Comment by SyberiaK** [comment]
Hey there, I finally got it, seems to be working fine.

![java_0R7lg6lPFM](https://github.com/SyberiaK/colorful-hex/assets/97897772/38719efd-4a48-4059-bfb3-1b932f1c6b4f)

Expect a new release in few hours!

**Comment by SyberiaK** [comment]
v1.1.0, featuring **both tooltips and written books support**, is released for 1.19.2-1.20.2 on [Modrinth](https://modrinth.com/mod/colorful-hex), [Curseforge](https://curseforge.com/minecraft/mc-mods/colorful-hex) and [GitHub](https://github.com/SyberiaK/colorful-hex/releases/tag/1.1.0_(1.19.2-1.20.2)).

**Comment by ExiledLizard** [comment]
Yooo! Thanks! I think others will find this enhancement helpful!

**Comment by ExiledLizard** [comment]
Also, does it work with item's lore, @SyberiaK?

**Comment by SyberiaK** [comment]
If it's the part of tooltips - sure it does.
